AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy Quem Disse Game - Static Website'

Parameters:
  ProjectName:
    Type: String
    Default: quem-disse-game
    Description: Nome do projeto

Resources:
  GameBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${AWS::AccountId}-${AWS::Region}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  GameBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GameBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${GameBucket}/*'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt GameBucket.RegionalDomainName
            Id: !Sub 'S3-${GameBucket}'
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub 'S3-${GameBucket}'
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 3600
          MaxTTL: 86400
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            RestrictionType: none

Outputs:
  WebsiteURL:
    Description: URL do website S3
    Value: !GetAtt GameBucket.WebsiteURL
    
  CloudFrontURL:
    Description: URL do CloudFront
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    
  S3BucketName:
    Description: Nome do bucket S3
    Value: !Ref GameBucket